apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-mental-health-app
  namespace: remmanuel
  annotations:
spec:
  ingressClassName: traefik
  rules:
    - host: pakcarik.petra.ac.id
      http:
        paths:
          - path: /chatbot-mental-health
            pathType: Prefix
            backend:
              service:
                name: chatbot-mental-health-service
                port:
                  name: streamlit-http
