apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-mental-health
  labels:
    app: chatbot-mental-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-mental-health
  template:
    metadata:
      labels:
        app: chatbot-mental-health
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: chatbot
        image: lionzwarrior10/chatbot-mental-health-old:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
          name: streamlit-http
          protocol: TCP
        - containerPort: 8000
          name: metrics-http
          protocol: TCP
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-headless-service:27017"
        - name: QDRANT_URL
          value: "http://qdrant-headless-service:6333"
        - name: OLLAMA_URL
          value: "http://ollama-model-headless-service:11434"
        resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "8"
              memory: "16Gi"

