apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: remmanuel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.8
        ports:
        - name: ollama-http
          containerPort: 8080
        - name: qdrant-tcp
          containerPort: 6333
        - name: mongo-tcp
          containerPort: 27017
        - name: stats
          containerPort: 1936
        volumeMounts:
        - name: haproxy-config-volume
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
      volumes:
      - name: haproxy-config-volume
        configMap:
          name: haproxy-config
