apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-nas-pv-remmanuel
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /media/nfs-codex/hpc/public/remmanuel
    server: nas
    readOnly: false
