apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: remmanuel
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017