apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-nas-pvc-remmanuel
  namespace: remmanuel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: mongodb-nas-pv-remmanuel
