apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-servicemonitor
  namespace: remmanuel 
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  namespaceSelector:
    matchNames:
    - gpu-operator 
  endpoints:
  - port: gpu-metrics
    interval: 30s
    path: /metrics
