apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-model-pv
  namespace: remmanuel
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ollama-nfs
  nfs:
    path: /media/nfs-codex/hpc/public/remmanuel
    server: nas
    readOnly: false
