apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-pvc
  namespace: remmanuel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ollama-nfs
