apiVersion: v1
kind: Service
metadata:
  name: ollama-llama31-service
  namespace: remmanuel
  labels:
    app: ollama-llama31
spec:
  selector:
    app: ollama-llama31
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
      nodePort: 31400
  type: NodePort 