apiVersion: v1
kind: Service
metadata:
  name: ollama-model-service
  namespace: remmanuel
spec:
  selector:
    app: ollama-model
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
