apiVersion: v1
kind: Service
metadata:
  name: ollama-openchat-service
  namespace: remmanuel
  labels:
    app: ollama-openchat
spec:
  selector:
    app: ollama-openchat
  ports:
    - name: openchat-api
      protocol: TCP
      port: 11434
      targetPort: 11434
      nodePort: 31401
  type: NodePort 