apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-model-custom-hpa
  namespace: remmanuel
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: ollama-model-custom-hpa
  template:
    metadata:
      labels:
        app: ollama-model-custom-hpa
    spec:
      serviceAccountName: ollama-model-custom-hpa
      containers:
        - name: autoscaler
          image: lionzwarrior10/ollama-model-custom-hpa:latest
          imagePullPolicy: Always
