apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-llama31-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /media/nfs-codex/hpc/public/remmanuel
    server: nas
    readOnly: false
