apiVersion: v1
kind: ServiceAccount
metadata:
  name: openchat-custom-hpa
  namespace: remmanuel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: remmanuel
  name: openchat-custom-autoscaler-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openchat-custom-hpa-rb
  namespace: remmanuel
subjects:
  - kind: ServiceAccount
    name: openchat-custom-hpa
    namespace: remmanuel
roleRef:
  kind: Role
  name: openchat-custom-autoscaler-role
  apiGroup: rbac.authorization.k8s.io
