apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: remmanuel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
            - containerPort: 6334
          volumeMounts:
            - name: qdrant-persistent-storage
              mountPath: /data/db
      volumes:
        - name: qdrant-persistent-storage
          persistentVolumeClaim:
            claimName: qdrant-nas-pvc-remmanuel