apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: remmanuel
spec:
  type: NodePort
  selector:
    app: qdrant
  ports:
    - protocol: TCP
      port: 6333
      targetPort: 6333
      nodePort: 30033