---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streamlit-custom-hpa
  namespace: remmanuel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: streamlit-custom-autoscaler-role
  namespace: remmanuel
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streamlit-custom-hpa-rb
  namespace: remmanuel
subjects:
- kind: ServiceAccount
  name: streamlit-custom-hpa
  namespace: defaremmanuelult
roleRef:
  kind: Role
  name: streamlit-custom-autoscaler-role
  apiGroup: rbac.authorization.k8s.io