[mongo]
connection_string = "mongodb://127.0.0.1:27017"

[qdrant]
url = "http://127.0.0.1:6333"
api_key = ""

[ollama]
models = ["llama3.1:latest", "openchat:latest"]
url = ["http://127.0.0.1:11434", "http://127.0.0.1:114345"]